const STORAGE_KEY="todo-tasks-v1";
const taskInput=document.querySelector("#task-input"),addTaskButton=document.querySelector("#add-task"),pendingList=document.querySelector("#pending-list"),completedList=document.querySelector("#completed-list"),pendingCount=document.querySelector("#pending-count"),completedCount=document.querySelector("#completed-count"),pendingEmpty=document.querySelector("#pending-empty"),completedEmpty=document.querySelector("#completed-empty"),taskTemplate=document.querySelector("#task-template");
let tasks=load();
function load(){try{const saved=localStorage.getItem(STORAGE_KEY),parsed=saved?JSON.parse(saved):[];return Array.isArray(parsed)?parsed.filter(t=>t&&typeof t.id==="string"&&typeof t.text==="string"&&typeof t.done==="boolean"):[]}catch{return[]}}
function save(){try{localStorage.setItem(STORAGE_KEY,JSON.stringify(tasks))}catch{}}
function createTask(text){const now=new Date().toISOString();return{id:crypto.randomUUID?crypto.randomUUID():String(Date.now()+Math.random()),text,done:false,added:now,completed:null}}
function formatDate(value){if(!value)return"";const date=new Date(value);if(Number.isNaN(date.getTime()))return"";return new Intl.DateTimeFormat(undefined,{dateStyle:"medium",timeStyle:"short"}).format(date)}
function addTask(){const text=taskInput.value.trim();if(!text){taskInput.focus();return}tasks.unshift(createTask(text));taskInput.value="";save();render();taskInput.focus()}
function toggleTask(id,done){const task=tasks.find(item=>item.id===id);if(!task)return;task.done=done;task.completed=done?new Date().toISOString():null;save();render()}
function deleteTask(id){tasks=tasks.filter(task=>task.id!==id);save();render()}
function startEdit(task,textElement,actionsElement){const form=document.createElement("form");form.className="edit-form";const input=document.createElement("input");input.type="text";input.maxLength=200;input.value=task.text;input.setAttribute("aria-label","Edit task");const saveButton=document.createElement("button");saveButton.type="submit";saveButton.className="save-button";saveButton.textContent="Save";const cancelButton=document.createElement("button");cancelButton.type="button";cancelButton.className="cancel-button";cancelButton.textContent="Cancel";form.append(input,saveButton,cancelButton);textElement.replaceWith(form);actionsElement.hidden=true;input.focus();input.select();const finish=shouldSave=>{const value=input.value.trim();if(shouldSave&&value){task.text=value;save()}render()};form.addEventListener("submit",event=>{event.preventDefault();finish(true)});cancelButton.addEventListener("click",()=>finish(false));input.addEventListener("keydown",event=>{if(event.key==="Escape")finish(false)})}
function buildTask(task){const item=taskTemplate.content.firstElementChild.cloneNode(true);if(task.done)item.classList.add("completed");const checkbox=item.querySelector(".task-checkbox"),textElement=item.querySelector(".task-text"),metaElement=item.querySelector(".task-meta"),editButton=item.querySelector(".edit-button"),deleteButton=item.querySelector(".delete-button"),actions=item.querySelector(".task-actions");checkbox.checked=task.done;checkbox.setAttribute("aria-label",task.done?"Mark task as pending":"Mark task as completed");textElement.textContent=task.text;metaElement.textContent="Added "+formatDate(task.added)+(task.completed?" • Completed "+formatDate(task.completed):"");checkbox.addEventListener("change",()=>toggleTask(task.id,checkbox.checked));editButton.addEventListener("click",()=>startEdit(task,textElement,actions));deleteButton.addEventListener("click",()=>deleteTask(task.id));return item}
function render(){pendingList.replaceChildren();completedList.replaceChildren();const pending=tasks.filter(t=>!t.done),completed=tasks.filter(t=>t.done);pending.forEach(t=>pendingList.appendChild(buildTask(t)));completed.forEach(t=>completedList.appendChild(buildTask(t)));pendingCount.textContent=pending.length+" pending";completedCount.textContent=completed.length+" completed";pendingEmpty.hidden=pending.length>0;completedEmpty.hidden=completed.length>0}
addTaskButton.addEventListener("click",addTask);taskInput.addEventListener("keydown",event=>{if(event.key==="Enter")addTask()});render();